# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: message.proto
# Protobuf Python Version: 5.28.3
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    28,
    3,
    '',
    'message.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\"$\n\rTensorMessage\x12\x13\n\x0btensor_data\x18\x01 \x01(\x0c\"\x1b\n\x0bTextMessage\x12\x0c\n\x04text\x18\x01 \x01(\t\"i\n\x07Message\x12$\n\x0ctext_message\x18\x01 \x01(\x0b\x32\x0c.TextMessageH\x00\x12(\n\x0etensor_message\x18\x02 \x01(\x0b\x32\x0e.TensorMessageH\x00\x42\x0e\n\x0cmessage_typeb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_TENSORMESSAGE']._serialized_start=17
  _globals['_TENSORMESSAGE']._serialized_end=53
  _globals['_TEXTMESSAGE']._serialized_start=55
  _globals['_TEXTMESSAGE']._serialized_end=82
  _globals['_MESSAGE']._serialized_start=84
  _globals['_MESSAGE']._serialized_end=189
# @@protoc_insertion_point(module_scope)
